name: 'firebaseDemo'
version: 0.0.1
description: A web app built using polymer.dart.
#author: Carl J. Mosca <carljmosca@gmail.com>
#homepage: https://stillhacking.blogspot.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: '>=0.10.0 <0.11.0'
  firebase: "^0.5.1"
  polymer: ">=0.15.1 <0.19.0"
  core_elements: ">=0.5.0 <0.8.0"
  paper_elements: ">=0.6.0 <0.8.0"
  message:   
transformers:
- polymer:
    entry_points:
    inline_stylesheets:
      lib/src/paper-shadow/paper-shadow.css: false
- $dart2js:
    $include: "**/*.polymer.bootstrap.dart"
